### ISSUE TITLE
get-shapefiles.py from openstreetmap-carto renamed in get-external-data.py

### ISSUE THREAD

**Issue by DirkHeinke** [switch2osm/switch2osm.github.io#124]
The script `scripts/get-shapefiles.py` does no longer exist. It seems to be replaced by `scripts/get-external-data.py` which also requires `sudo apt-get install python3-psycopg2` before.

**Comment by SomeoneElseOSM** [comment]
Yes - actually I think we had another issue for this, but I can't see it, so maybe it was just a comment elsewhere.

**Comment by SomeoneElseOSM** [comment]
I've addressed this in https://github.com/switch2osm/switch2osm.github.io/pull/125 .

For 18.04 and 20.04 I've updated the instructions, tested it, and changed the text slightly to reflect the lack of feedback that the "new" script gives.

For 16.04 I've added a caveat suggesting "you probably don't want to use this any more but here it still is if you really want to".
