### ISSUE TITLE
OSM Carto custom indexes required

### ISSUE THREAD

**Issue by kocio-pl** [switch2osm/switch2osm.github.io#150]
Since OSM Carto 5.3.0 custom indexes (`psql -d gis -f indexes.sql`) are required for performance and even before that they were recommended, but I lack it on all the Debian and Ubuntu manual pages. See:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/CHANGELOG.md#v530---2021-01-28
https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#custom-indexes

**Comment by SomeoneElseOSM** [comment]
Thanks.  I've done the Debian page, and will have a look at Ubuntu 20.04 a bit later on.  With regard to the Docker version, https://github.com/Overv/openstreetmap-tile-server/commit/9b2b67b07668c726235f395e137b58accef0c809 was merged into that a while back.  Does that look OK?

**Comment by kocio-pl** [comment]
Yes, and thanks a lot for a fast reaction! :+1:

**Comment by SomeoneElseOSM** [comment]
I've done Ubuntu 20.04 in https://github.com/switch2osm/switch2osm.github.io/pull/154 .
