### ISSUE TITLE
Figure out hosting

### ISSUE THREAD

**Issue by pnorman** [switch2osm/switch2osm.github.io#17]
Github pages works for https on github.io sites, but not custom domains, so it'll need a different hosting option.

**Comment by matkoniecz** [comment]
> Github pages works for https on github.io sites, but not custom domain

see https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by harry-wood** [comment]
Also see here https://help.github.com/articles/troubleshooting-custom-domains/#https-errors Guess it became possible more recently.

Usage limits/speed of github pages might be a factor. [Usage limits](https://help.github.com/articles/what-is-github-pages/#usage-limits) are 100GB per month. No idea if the live switch2osm.org is likely to exceed that.

...but anyway I imagine OWG will have opinions and preferred set-up when the time comes for this repo to go live. Currently the wordpress install is managed with a chef recipe:  https://github.com/openstreetmap/chef/tree/master/cookbooks/switch2osm Maybe it simply involves swapping that for a jekyll recipe

**Comment by matkoniecz** [comment]
> Guess it became possible more recently.

I setup my own https://mapsaregreat.com/ on https with no trouble whatsoever (it redirected from https to https by default, there was option in repo settings to force https).

**Comment by SomeoneElseOSM** [comment]
I think that we can close this now that https://switch2osm.org/ has moved over to the content from here.
