### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by danieldegroot2** [switch2osm/switch2osm.github.io#215]
[Two files](https://github.com/switch2osm/switch2osm.github.io/search?q=tile.openstreetmap.org) are still using an old tile URL. I would suggest changing them to the preferred URL, see https://github.com/openstreetmap/operations/issues/737

**Comment by SomeoneElseOSM** [comment]
I thought I'd found all of those - by all means send a pull request through!
