### ISSUE TITLE
Visual redesign

### ISSUE THREAD

**Issue by pnorman** [switch2osm/switch2osm.github.io#3]
Some thoughts on information for when asking 
- An appearance distinct from the sites of other OSM companies
- Allowing the growth of the number of articles without menu crowding (i.e. use submenus or a similar technique)
- Articles within a category will have a page providing an overview of the category
- Formatting will need to allow for source code inline and in blocks, pull quotes
- Updating the current content will be done independently
- There's nothing inherently wrong with the current live design, except it's built around WordPress

What we need to do
- [x] Add more existing content
- [x] Prepare a message
- [x] Write message to OSM community looking for design help
- [ ] Write to companies involved in OSM asking for time of a designer?

cc @systemed

**Comment by pnorman** [comment]
Message draft

> Switch2OSM is undergoing a rewrite to allow a different contribution model. As part of this we had to switch from the existing WordPress design to one using Jekyll. This requires a new visual design, and we're looking for help from a designer.

> This is independent of content changes, so you don't need to know anything about the subjects the guides cover.

> There's some more information at https://github.com/switch2osm/switch2osm.github.io/issues/3, and the content can be seen at http://switch2osm.github.io/ with just a default Jekyll style.

> If you're interested in helping, please get in touch. A company could also help by letting one of their graphic designers work on it.

**Comment by ThomasG77** [comment]
Closing the issue with #60 merged PR.
Feel free to react if you feel it
