### ISSUE TITLE
Replace references to MapQuest open tiles

### ISSUE THREAD

**Issue by pnorman** [switch2osm/switch2osm.github.io#4]
MapQuest open tiles are probably not what we want to be refering people to, given the frequently extreme delay they've had.

In addition

* There is uncertainty over future usage limits
* The MQ Open Dev pages return 404 errors

In places tile.osm.org is used, and that's probably the best option for now.

**Comment by pnorman** [comment]
We definitely need to remove references now

**Comment by ThomasG77** [comment]
Done. Feel free to reopen @pnorman if I miss something
