### ISSUE TITLE
Passing off control to someone else

### ISSUE THREAD

**Issue by pnorman** [switch2osm/switch2osm.github.io#44]
I don't have the time and energy to work on switch2osm, and haven't for some time. Rather than blocking work, I'd like to pass this effort off to someone else who has the energy to take it forwards.

cc @systemed @SomeoneElseOSM

**Comment by harry-wood** [comment]
I'd like to help. I think @systemed is still keen too. We chatted about it in Milan. I also chatted with two other people who were volunteering to help if they can: The guy from Klakontech (he's keen to expand vector tile related tutorials) and Redon Skikuli and his team at Tirana Hackerclub (Seems to include some good web design talent!).

**Comment by harry-wood** [comment]
Lots of recent activity and the jekyll flavoured http://switch2osm.org is live! I think we can close this one now

**Comment by SomeoneElseOSM** [comment]
Closing as no longer a relevant issue.
