### ISSUE TITLE
add Gisgraphy to geocoding providers on the 

### ISSUE THREAD

**Issue by gisgraphy** [switch2osm/switch2osm.github.io#45]
I am a user of Openstreetmap since 2006, and I am starting using it very early. in 2006, Things were different. The softwares stack was not what it is now

So for personal needs, I have started to code an open source geocoder called Gisgraphy. Gisgraphy is now a mature project that is heavily used and can be run totally offline and / or can be tested for free at https://services.gisgraphy.com (to be totally transparent I also propose some hosting service to pay all the servers and stuff around it). There are some importers that allow importing several Datasets (OpenAddresses, OSM, Geonames,Quattroshapes and Tiger to come soon).

I also provide for free some PBF extracts for 256 countries code (https://download.gisgraphy.com/openstreetmap/pbf/)

I would like to know if You could put a link to the project on the https://switch2osm.org/other-uses/ and https://switch2osm.org/fr/autres-utilisations/ pages.

Something like :

"Gisgraphy : Open source geocoder that provides API / webservices of forward and reverse geocoding with auto-completion, interpolation, location Bias, find nearby, all can be run offline or as hosted solutions. It provide some importers for Openstreetmap but also Openadresses, Geonames, and more. "

or in french

"Gisgraphy : Geocodeur open source fournissant des webservices de géocoding (avec auto-complétion, interpolation, recherche à proximité) qui peuvent être utilisés hors ligne ou en tant que service hébergés. Il se base sur des données ouvertes comme Openstreetmap, Openadresses, Geonames."

Feel free to correct things, English is not my mother tongue but I am sure you already see that

you can try the demo at https://services.gisgraphy.com and see the website at https://www.gisgraphy.com

Let me know if you got questions
Best regards from France
David

**Comment by systemed** [comment]
Added to https://switch2osm.org/providers - sorry for the delay.

**Comment by gisgraphy** [comment]
HiMany many thanks. Is it possible to add to other uses page in geocoding section? Thanks againDavid Masclet-------- Message original --------Objet : Re: [switch2osm/switch2osm.github.io] add Gisgraphy to geocoding providers on the (#45)De : Richard Fairhurst À : "switch2osm/switch2osm.github.io" Cc : gisgraphy ,Author Added to https://switch2osm.org/providers - sorry for the delay.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/switch2osm/switch2osm.github.io","title":"switch2osm/switch2osm.github.io","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/switch2osm/switch2osm.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@systemed in #45: Added to https://switch2osm.org/providers - sorry for the delay."}],"action":{"name":"View Issue","url":"https://github.com/switch2osm/switch2osm.github.io/issues/45#issuecomment-408788959"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/switch2osm/switch2osm.github.io/issues/45#issuecomment-408788959",
"url": "https://github.com/switch2osm/switch2osm.github.io/issues/45#issuecomment-408788959",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [switch2osm/switch2osm.github.io] add Gisgraphy to geocoding providers on the  (#45)",
"sections": [
{
"text": "",
"activityTitle": "**Richard Fairhurst**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@systemed",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"switch2osm/switch2osm.github.io\",\n\"issueId\": 45,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/switch2osm/switch2osm.github.io/issues/45#issuecomment-408788959"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 342701755\n}"
}
],
"themeColor": "26292E"
}
]
