### ISSUE TITLE
18.04 comments

### ISSUE THREAD

**Issue by systemed** [switch2osm/switch2osm.github.io#49]
from mail:

````

Setting up your webserver
___________________________

addition #1:
at the end of renderd.conf press [ENTER] so that the line MAXZOOM=20 is not the ast line. Otherwise you get an error message ca. "line is to long" from renderd

addition #2:
> sudo mkdir /var/run/renderd
> sudo chown renderaccount /var/run/renderd
see https://stackoverflow.com/questions/16851034

addition #3:
> chmod 777 /var/lib/mod_tile
see https://forum.openstreetmap.org/viewtopic.php?id=11330
````
[my_remarks__manually-building-a-tile-server-18-04-lt.pdf](https://github.com/switch2osm/switch2osm.github.io/files/2214304/my_remarks__manually-building-a-tile-server-18-04-lt.pdf)

**Comment by pnorman** [comment]
I'm pretty sure the chmod 777 is a bad idea, but haven't run through a setup in awhile.

**Comment by SomeoneElseOSM** [comment]
Re addition #1, there's already a trailing newline at the end of https://github.com/SomeoneElseOSM/mod_tile/blob/switch2osm/renderd.conf , so I wonder what editor was being used that caused that to be lost?  I'm guessing that something that changed the line termination (to ^M or ^M^L) could maybe cause a line-too-long issue, but without more info I'd just be guessing.

Re addition #2, the "Configuring Apache" section already has those lines.  I wonder if the emailer is using a mix and match of different sets of instructions, or two different accounts for different bits?

Re addition #3, you really don't need to do this unless you have a couple of different accounts needing to access that directory (and even if so, world+dog write access is unnecessary).  The https://forum.openstreetmap.org/viewtopic.php?id=11330 thread is from 2011 and does seem to be about multiple users accessing those tiles.
