### ISSUE TITLE
Add Champs-Libres in the provider page

### ISSUE THREAD

**Issue by nobohan** [switch2osm/switch2osm.github.io#50]
Champs-Libres (https://www.champs-libres.coop/), Belgium.

Champs-Libres.coop is a small IT company specialised in cartography and on the use of OSM. Would it be possible that Champs-Libres be mentioned on the provider page of switch2osm? Champs-Libres can actually propose OSM-based tile server to our customers.

For about 2 years, Champs-Libres has set up a tile server with the default Mapnik and the Humanitarian HDM style: https://carton2.entrouvert.org/. This tile server is available for the companies of the (French-speaking) network Libre-entreprise, that gathers IT company working with open-source software. It is used in production by several customers. 

Thanks!

**Comment by systemed** [comment]
Done :)
