### ISSUE TITLE
The French version of the Providers page is not updated

### ISSUE THREAD

**Issue by nobohan** [switch2osm/switch2osm.github.io#52]
Hi, 

https://switch2osm.org/providers/ is different of https://switch2osm.org/fr/prestatataires/.

Some French-speaking providers (Champs-Libres, Gisgraphy, Oslandia) are missing.

I wanted to fix the issue by myself but I cannot find where the French translation are. Actually other pages need some translations.

**Comment by ThomasG77** [comment]
I've done the correction on https://switch2osm.org website (I'm the French translator)
My 2 cents to help you understand current situation

The content on this repository is hosted at http://switch2osm.github.io.
It differs from https://switch2osm.org that use Wordpress
The plan from my understanding was to change current website with content from this repository but not enough effort from the community.
Currently seeking a lead e.g https://github.com/switch2osm/switch2osm.github.io/issues/44

**Comment by nobohan** [comment]
Merci!

Je pourrais aider sur les traductions en fr en utilisant Wordpress.

**Comment by SomeoneElseOSM** [comment]
When I looked at the French wordpress translation a week or so ago, and there was quite a bit more that was out of date.  Following a drastic graphical improvement we've moved the github version "live" (see https://github.com/switch2osm/switch2osm.github.io/pull/60 ).

I'll close this, but it's probably worth creating a new issue asking "how can we maintain translations" more generally.
