### ISSUE TITLE
Adding Stadia Maps as a provider for tiles

### ISSUE THREAD

**Issue by lseelenbinder** [switch2osm/switch2osm.github.io#58]
We've been operating a OSM-based map tile service for over a year now and have built a customer base. Could we be included in the list as follows?

Thank you!

- [Stadia Maps](https://stadiamaps.com), US

**Comment by lseelenbinder** [comment]
I'm more than happy to make a PR, but I understood from the readme an issue was preferred first.

**Comment by SomeoneElseOSM** [comment]
Thanks - I've just merged the PR for this.

**Comment by lseelenbinder** [comment]
Thanks all!
