### ISSUE TITLE
Drop "Getting started with Leaflet" 

### ISSUE THREAD

**Issue by simon04** [switch2osm/switch2osm.github.io#6]
The "Getting started with Leaflet" is
* not following Javascript best practices (w.r.t. loading of external libraries like ignore dependency management tools like bower.io, performing `eval` of server returned JSON, …)
* rather complex due to the dynamic fetching of POI for current viewport

In contrast, the [Leaflet Quick Start Guide](http://leafletjs.com/examples/quick-start.html) provides a nice stepwise introduction. So we might drop the chapter completely or strip it down to a very short example?

cc: @pnorman

**Comment by pnorman** [comment]
cc @systemed

**Comment by systemed** [comment]
Short stripped-down example sounds good.

Not overly keen on mandating use of bower though: s2o is meant to be about "here's what you need to get started", and having to understand bower/npm takes it further away from that. Simple old-style script includes are fine; people who know about dependency management will know how to use their preferred toolchain, but we shouldn't exclude people who don't.

**Comment by pnorman** [comment]
Against requiring bower for the guide.

I'm not sure about the Leaflet guide, it seems too focused on a specific provider with authentication

**Comment by pnorman** [comment]
Solved in #9
