### ISSUE TITLE
add OSMUK Talent Director to Providers list

### ISSUE THREAD

**Issue by jnicho02** [switch2osm/switch2osm.github.io#76]
The OSMUK Local Chapter run a "Talent Directory" where UK companies can be put in touch with UK OSM service providers. https://osmuk.org/professional-services/

Please add to the Providers list of the UK.

**Comment by jnicho02** [comment]
Developers do not wish to reference the Local Chapter.

**Comment by SomeoneElseOSM** [comment]
To be fair, in the context of this site OSM UK isn't "the local chapter"; it is "a local chapter". My understanding of the original purpose of this list (and I didn't create it, so I may be wrong) is that it was supposed to be an easier to use list than the equivalent ones in the OSM wiki - shorter, and with all the entries on it up to date and active.

The problem with the OSM UK page is that it's a vague "come and talk to us" one. It's exactly the sort of page that if I was buying for $dayjob or even just trying to call a plumber  I'd avoid.

There's definitely a case for pointing people who come to switch2osm at the OSM community, Depending on who they are an appropriate place might be OSMF's US-focused "Welcome Mat", or openstreetmap.community, or a specific community resource or local chapter.

I suspect that's a different page to this one, though.
