### ISSUE TITLE
broken link on serving-tiles

### ISSUE THREAD

**Issue by woodpeck** [switch2osm/switch2osm.github.io#83]
https://switch2osm.org/serving-tiles/ links to https://switch2osm.org/serving-tiles/using-an-all-in-one-solution/ which does not exist. Unsure if the link needs to change or needs to be removed hence unable to submit fix.

**Comment by ThomasG77** [comment]
From my viewpoint, it should be removed as it links to outdated content e.g when looking at Wayback Machine previous content https://web.archive.org/web/20190418070602/https://switch2osm.org/serving-tiles/using-an-all-in-one-solution/

**Comment by SomeoneElseOSM** [comment]
The probably needs to be something suggesting that many people find the "ecosystem" route (e.g. Mapbox) a good way to solve the problem.  Maybe that's this (former) page, maybe that's another one - needs a bit of thinking about.

**Comment by SomeoneElseOSM** [comment]
It looks like Richard's fixed the broken link, though, so I'll close this.
