### ISSUE TITLE
Adding Jawg as a tile provider

### ISSUE THREAD

**Issue by clementgayvallet** [switch2osm/switch2osm.github.io#94]
Jawg has been serving OSM based tiles for  more than 4 years. 

Can we be included in the list as **Development services and consulting** and **Tile hosting**?

Thank you :)

* [Jawg](https://www.jawg.io/), France

**Comment by SomeoneElseOSM** [comment]
Oops - already merged; forgot to close this issue.

**Comment by clementgayvallet** [comment]
Thank you!
