### ISSUE TITLE
About page "Serving Tiles"

### ISSUE THREAD

**Issue by Silka123** [switch2osm/switch2osm.github.io#98]
On the "Serving Tiles" page under "The options", the link number 2 ("Build a tile server using packages") leads to 404. Fix it?

**Comment by SomeoneElseOSM** [comment]
That link works for me - it goes to https://switch2osm.org/serving-tiles/building-a-tile-server-from-packages/ .

We probably will retire that page very soon though, because it is only for Ubuntu versions out of support.

**Comment by Silka123** [comment]
Look carefully, the link on the site now leads to the following page: https://switch2osm.org/serving-tiles/ubuntu-14-building-a-tile-server-from-packages/

You have given as an example a completely different link.
